# file: C:\Users\rober\AppData\Roaming\Python\Python313\site-packages\werkzeug\exceptions.py
# hypothesis_version: 6.137.1

[400, 401, 403, 404, 405, 406, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423, 424, 428, 429, 431, 451, 500, 501, 502, 503, 504, 505, ', ', '<br>', '???', 'Allow', 'Content-Range', 'Content-Type', 'Retry-After', 'Unknown Error', 'WSGIResponse', 'WWW-Authenticate', 'bytes']